require("dotenv").config();

module.exports = {
  appName: process.env.APP_NAME,
  port: process.env.PORT,
  nodeEnv: process.env.NODE_ENV,
  frontendUrl: process.env.FRONTEND_URL,
  mlServiceUrl: process.env.ML_SERVICE_URL,
  mlServiceApiKey: process.env.ML_SERVICE_API_KEY,
  mongodbUri: process.env.MONGODB_URI,
  jwtSecret: process.env.JWT_SECRET,
  jwtExpiresIn: process.env.JWT_EXPIRES_IN,
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  linkedinClientId: process.env.LINKEDIN_CLIENT_ID,
  linkedinClientSecret: process.env.LINKEDIN_CLIENT_SECRET,
  facebookClientId: process.env.FACEBOOK_CLIENT_ID,
  facebookClientSecret: process.env.FACEBOOK_CLIENT_SECRET,
  cookiePassword: process.env.COOKIE_PASSWORD,
  smptUser: process.env.SMTP_USER,
  smptPass: process.env.SMTP_PASS,
  gcpPathSecret: process.env.GCP_PATH_SECRET,
  gcpProjectId: process.env.GCP_PROJECT_ID,
  gcpBucketName: process.env.GCP_BUCKET_NAME,
};
