name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: hireonai-backend
  REGION: asia-southeast2 # Jakarta region

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create Cloud Storage service account key file
      run: |
        mkdir -p src/keys
        echo '${{ secrets.GCP_STORAGE_SA_KEY }}' > src/keys/gcs-service-account.json
      
    - name: Auth with Google Cloud (Deployment)
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_DEPLOY_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'beta'
        
    - name: Configure Docker for GCP
      run: gcloud auth configure-docker
        
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} -f Dockerfile.cloudrun .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        env_vars: |
          APP_NAME=${{ secrets.APP_NAME }}
          NODE_ENV=production
          PORT=8080
          FRONTEND_URL=${{ secrets.FRONTEND_URL }}
          ML_SERVICE_URL=${{ secrets.ML_SERVICE_URL }}
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          LINKEDIN_CLIENT_ID=${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET=${{ secrets.LINKEDIN_CLIENT_SECRET }}
          FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}
          FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}
          COOKIE_PASSWORD=${{ secrets.COOKIE_PASSWORD }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASS=${{ secrets.SMTP_PASS }}
          GCP_PATH_SECRET=../keys/gcs-service-account.json
          GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }}
        
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
